\documentclass{article}
\begin{document}
<<>>=
#| label: setup
#| include: false
if (!require('diagram')) install.packages('diagram', repos = 'http://cran.rstudio.com')
<<>>=
#| label: read-demo
library(knitr)
library(diagram)
read_demo('flowchart', package = 'diagram',
          labels = 'demo-flowchart')
<<>>=
#| label: demo-flowchart
#| dev: tikz
#| cache: true
#| tidy.opts: !expr list(width = 60)
@
\end{document}
